### ISSUE TITLE
Universal build fails with warning SHAs are not identical

### ISSUE THREAD

**Issue by NielsLeenheer** [electron/universal#10]
```
Error: Expected all non-binary files to have identical SHAs when creating a universal build but "Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/vk_swiftshader_icd.json" did not
```

Which is weird, since when running shasum manually it tells me that the files are identical:

```
shasum Salonhub-darwin-*64/Salonhub.app/Contents/Frameworks/Electron\ Framework.framework/Versions/A/Libraries/vk_swiftshader_icd.json 
8734c383f004e365904068c9cde7999aab0b54c6  Salonhub-darwin-arm64/Salonhub.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/vk_swiftshader_icd.json
8734c383f004e365904068c9cde7999aab0b54c6  Salonhub-darwin-x64/Salonhub.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/vk_swiftshader_icd.json
```

**Comment by NielsLeenheer** [comment]
It appears the problem is present in 1.0.2 and 1.0.3. Rolling back to 1.0.1 fixes the issue.

**Comment by MarshallOfSound** [comment]
Hm, I wonder if my rewrite to make the sha method async by using streams has a flaw.  It worked with my local apps

**Comment by NielsLeenheer** [comment]
A fix is available in PR #11 😀

**Comment by MarshallOfSound** [comment]
Fixed in  477a52e

**Comment by ishowshao** [comment]
`Contents/_CodeSignature/CodeResources` always different

**Comment by NielsLeenheer** [comment]
Are you perhaps signing the binaries first? That would cause them to be different. 

The universal binary should be created from unsigned arm64 and x64 binaries. And finally the universal binary needs to be signed and notarized.

**Comment by ishowshao** [comment]
no, not signed first, i see the xml in `Contents/_CodeSignature/CodeResources` , they are always different
`
		<key>Frameworks/Electron Framework.framework</key>
		<dict>
			<key>cdhash</key>
			<data>
			zftqvls6kWOPLaw3yZLtpnJCzFs=
			</data>`

**Comment by ishowshao** [comment]
i think : they come from different release `https://github.com/electron/electron/releases/download/v11.0.3/electron-v11.0.3-mas-arm64.zip` and `https://github.com/electron/electron/releases/download/v11.0.3/electron-v11.0.3-mas-x64.zip`

**Comment by ishowshao** [comment]
it seems electron-builder will sign...

**Comment by ishowshao** [comment]
but, how can i get the .app before electron-builder build

**Comment by jwoo0122** [comment]
> but, how can i get the .app before electron-builder build

You can use electron-packager for generate .app file.
