### ISSUE TITLE
Missing LICENSE file in the repo of ver 1.0.4

### ISSUE THREAD

**Issue by itsuki-murata** [electron/universal#107]
Currently I'm using @electron/universal version 1.0.4, but can't find a LICENSE file in the repo of ver 1.0.4.
Could you add the LICENSE file in the repo of ver 1.0.4?
Or is it possible to use the LICENSE file of the latest version as the license for ver 1.0.4?
Thanks in advance.

**Comment by dsanders11** [comment]
Hi @itsuki-murata! It looks like the latest releases have the expected LICENSE file - v1.0.4 was released 4 years ago, updating to a newer version should resolve your issue.
