### ISSUE TITLE
Add option to pick one asar, instead of keeping both

### ISSUE THREAD

**Issue by NielsLeenheer** [electron/universal#2]
It would be nice to have an option which you can use to configure what to do with the two asar files. Currently the default behaviour is to keep them both and use a runtime check to determine which to run.

The asar of our app quite big, about 30 MB and the arm64 and x64 versions are identical. In our case the default behaviour would add an unneeded 30 MB to our .app.

Perhaps four options:
x64, arm64, both and auto.

With auto doing a check to see if the two asar's are identical. If identical, pick one. And if different, keep both.

**Comment by NielsLeenheer** [comment]
Actually...

Adding an option is not really necessary. Just make the 'auto' option the default behaviour and it will automatically work in both cases.

**Comment by MarshallOfSound** [comment]
@NielsLeenheer are the SHAs of your asar files the same? If so then yeah, adding that kind of optimization makes sense to me

**Comment by NielsLeenheer** [comment]
Yes, the SHAs are identical.

**Comment by MarshallOfSound** [comment]
Fixed in 82acb6f
