### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by nvdai2401** [electron/universal#33]
Thank you for an awesome library!
 
I want to build a universal application. By reading this [article](https://www.electronjs.org/blog/apple-silicon), I know `@electron/universal` can do this for me. But I cannot find any instructions on how to use this library with `electron-builder`.
Could you please give me an example of how to use `@electron/universal` with `electron-builder`?

**Comment by Slapbox** [comment]
Did you resolve this and not share the solution? :(

**Comment by nvdai2401** [comment]
@Slapbox You can easily add `universal` to the build config of your app like this:
```json
	"mac": {
     ...
      "target": [
        "zip",
        {
          "target": "dmg",
          "arch": [
            "x64",
            "universal"
          ]
        }
      ],
      ..
    },
```

**Comment by javierguzman** [comment]
Does anyone have an example with electron forge? I have the above snippet but it does not work. I only get the message "[STARTED] Packaging for x64 on darwin" but it it does not make a universal build. My build command is "electron-forge make --platform darwin"
