### ISSUE TITLE
Resources Not Found when Using Native Dependencies

### ISSUE THREAD

**Issue by jakobvogel** [electron/universal#35]
Hello! First of all, many thanks for your work on _Electron_ and its many sub-projects. We appreciate this a lot.

Disclaimer: I am aware that earlier issues relating to different _asar_ files have been discussed before, but I did not find this particular case (or a solution) and decided to open a new issue. (Particularly pull-request #34 seems to tackle a very similar – if not the same – problem.)

## TL;DR

When the universal app ends up with a "switch" `app.asar` and two architecture-specific files `app-arm64.asar` and `app-x64.asar`, the app will attempt to load files (for instance during `window.loadFile('index.html')` with `window` a `BrowserWindow`) from `app.asar` rather than the architecture-specific file, leading to a loading failure.

For a minimal example based on the quick-start example and using `electron-builder`, see: https://github.com/jakobvogel/universal-electron-test

<img width="912" alt="Screenshot 2021-12-22 at 20 40 20" src="https://user-images.githubusercontent.com/36069303/147148874-b6cfcfc9-8e04-4445-b800-bdf1841af3fb.png">

## Background

In our app, we use `keytar` for password storage. Its prebuilt binaries are architecture specific. They end up in the `app.asar` files, causing the SHAs to differ while everything else contained in the two files is the same. Therefore, the universal build includes the architecture-specific switch, and the universal app is able to load, including the `keytar` dependency. However, when attempting to load a local HTML file for rendering the app, the app attempts to read from the (virtually empty) switch `app.asar` while the data is contained `app-arm64.asar` and `app-x64.asar`. The two original architecture-specific apps both work.

I am wondering whether there is a simple solution to this.
- Is it possible to "route" local files directly in the electron app?
- Is it possible to extend the "switch" _app.asar_ to "route" resource requests to the architecture-specific _asar_?
- Is it possible to "repack" the two raw _asar_ files such that joint resources end up in the switch `app.asar`, while architecture-specific dependencies remain in `app-arm64.asar` and `app-x64.asar`?

The only other alternative would be to build a universal `keytar.node` (hopefully) causing the two _asar_ files to be equal again, correct? (Assuming that node files can be universal after all, and that the build system could be forced to use a universal build while creating the two original architecture-specific apps.)

Thanks again for your input.

**Comment by MarshallOfSound** [comment]
The fact it's loading your HTML file from `app.asar` implies a manual path resolution issue somewhere in your code or electron-builders code.  `loadFile` does relative path resolution and shouldn't search `app.asar` automatically.

You could try working around this by doing path resolution yourself with `path.resolve(__dirname, 'index.html')`

**Comment by jakobvogel** [comment]
Many thanks for your comment @MarshallOfSound — manual path resolution via `__dirname` really fixes the issue. (Yeah! 😊) Your help is greatly appreciated! 🙇‍♂️
