### ISSUE TITLE
The renamed app directories should not get an .app extension 

### ISSUE THREAD

**Issue by NielsLeenheer** [electron/universal#5]
The app directories are currently renamed to x64.app and arm64.app. But .app has a special meaning in macOS, causing these directories to appear as a corrupt application. Perhaps it is safer to rename them to app-x64 and app-arm64 or something similar.

**Comment by MarshallOfSound** [comment]
Ah good call, tbh I've been testing this with an app that uses ASARs so the path for non-asar apps isn't well tested at all

**Comment by MarshallOfSound** [comment]
Fixed in 82acb6f
