### ISSUE TITLE
Security vulnerability in minimatch@3.0.4

### ISSUE THREAD

**Issue by Itzdan0ul** [electron/universal#56]
Hi! Currently a vulnerability has been reported in the "high" severity level minimatch dependency.

Security vulnerability reported in `<=minimatch@3.0.4`: [minimatch ReDoS vulnerability](https://github.com/advisories/GHSA-f8q6-p94x-37v3)

Vulnerabilities when doing `yarn audit` or `npm audit`:

![redos_vulnerability](https://user-images.githubusercontent.com/69698529/197273597-39285b61-9261-492c-af37-58952f4cbbab.JPG)

**Comment by MarshallOfSound** [comment]
Fixed in https://github.com/electron/universal/releases/tag/v1.3.4
