### ISSUE TITLE
Uncaught ReferenceError, as app is not defined as of @electron/universal@1.4.2

### ISSUE THREAD

**Issue by BaldvinTh** [electron/universal#80]
### Electron Forge version
6.4.2

### Expected behavior

Application built with universal architecture runs the correct architecture

### Actual behavior

Uncaught exception as the script tries to utilize a function from undefined variable.
Issue introduced in [v1.4.2](https://github.com/electron/universal/blob/v1.4.2/entry-asar/has-asar.js#L12)

### Steps to reproduce

Build a universal application, make & run it

### Additional information

![image](https://github.com/electron/universal/assets/14164010/7635814c-2989-43f2-bf72-e6932b5832b9)

**Comment by soroushm** [comment]
same here
look like in [entry-asar/has-asar.js](https://github.com/electron/universal/blob/fe1a0e06b014951f92a659095ad9c1ca607a94b3/entry-asar/has-asar.js) use app but is not imported so we are getting this error

const appPath = app.getAppPath();
