### ISSUE TITLE
Mac App Store  Compatibility  infomation

### ISSUE THREAD

**Issue by gaodeng** [electron/universal#9]
apple numbers 
macOS 10.15 or later
https://apps.apple.com/cn/app/numbers/id409203825?l=en&mt=12
![Screen Shot 2020-11-20 at 2 40 42 PM](https://user-images.githubusercontent.com/1118249/99767837-b3d54f80-2b3e-11eb-81fd-472ddfd4a6ee.png)
moon fm
OS X 10.10.0 or later, 64-bit processor
It's actually a universal binary
https://apps.apple.com/us/app/moon-fm-premium-podcast-app/id1465712037?mt=12
![Screen Shot 2020-11-20 at 2 41 09 PM](https://user-images.githubusercontent.com/1118249/99767844-b6d04000-2b3e-11eb-9e82-59c0bfa80228.png)

**Comment by MarshallOfSound** [comment]
I think this is a side effect of universal apps.  The x64 slice supports 10.10 and up but by definition the arm64 slice only supports 10.15 and up.  Not sure where apple is pulling those numbers from though so not sure what might need to change here

**Comment by gaodeng** [comment]
@MarshallOfSound 
Ulysses
https://apps.apple.com/cn/app/ulysses/id1225570693?l=en&mt=12  
Compatibility  macOS 10.14.4 or later
lipo -info /Applications/UlyssesMac.app/Contents/MacOS/UlyssesMac 
Architectures in the fat file: /Applications/UlyssesMac.app/Contents/MacOS/UlyssesMac are: x86_64 arm64

**Comment by gaodeng** [comment]
This looks like it might be relevant. It's from Info.plist
```
        <key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>

```

**Comment by gaodeng** [comment]
> This looks like it might be relevant. It's from Ulysses's Info.plist
> 
> ```
>         <key>CFBundleSupportedPlatforms</key>
> 	<array>
> 		<string>MacOSX</string>
> 	</array>
> ```

Just tried to update a version of the app which info.plist contains CFBundleSupportedPlatforms. Looks like it has nothing to do with CFBundleSupportedPlatforms

**Comment by kanishk-zaanu** [comment]
How were you able to submit your app, I don't know to convert .app into .pkg for it to be submitted by transporter to app connect.
